'use client'

import { useEffect, useMemo, useState } from 'react'
import { Check, ChevronLeft, ChevronRight, Clock3, Download, FileText, LockKeyhole, Menu, Phone, ShieldCheck, X } from 'lucide-react'

const states = ['Andhra Pradesh','Arunachal Pradesh','Assam','Bihar','Chhattisgarh','Goa','Gujarat','Haryana','Himachal Pradesh','Jharkhand','Karnataka','Kerala','Madhya Pradesh','Maharashtra','Manipur','Meghalaya','Mizoram','Nagaland','Odisha','Punjab','Rajasthan','Sikkim','Tamil Nadu','Telangana','Tripura','Uttar Pradesh','Uttarakhand','West Bengal','Andaman and Nicobar Islands','Chandigarh','Dadra and Nagar Haveli and Daman and Diu','Delhi','Jammu and Kashmir','Ladakh','Lakshadweep','Puducherry']
const categories = ['UPI Related Fraud','Internet Banking Related Fraud','Fraud Call / Vishing','Aadhar Enabled Payment System (AEPS) Fraud','Business Email Compromise / Email Takeover','Debit / Credit Card Fraud / SIM Swap Fraud','Demat / Depository Fraud','E-Wallet Related Fraud']
const banks = ['State Bank of India','Punjab National Bank','Bank of Baroda','Canara Bank','Union Bank of India','Bank of India','Indian Bank','Central Bank of India','UCO Bank','Bank of Maharashtra','Indian Overseas Bank','Punjab & Sind Bank','HDFC Bank','ICICI Bank','Axis Bank','Kotak Mahindra Bank','IndusInd Bank','Yes Bank','IDFC First Bank','Federal Bank','South Indian Bank','Karur Vysya Bank','City Union Bank','Tamilnad Mercantile Bank','Dhanlaxmi Bank','RBL Bank','Bandhan Bank','AU Small Finance Bank','Equitas Small Finance Bank','Ujjivan Small Finance Bank','Jana Small Finance Bank','Paytm Payments Bank','Airtel Payments Bank','India Post Payments Bank','Fino Payments Bank','Jio Payments Bank','PhonePe (wallet)','Google Pay (wallet)','Amazon Pay (wallet)','Other']
const platforms = ['WhatsApp','Telegram','Instagram','Facebook','Twitter/X','Snapchat','YouTube','LinkedIn','Email (Gmail/Outlook)','Phone Call','SMS','Online Shopping Website','Dating App','Gaming Platform','Other']

type FormData = { mobile:string; name:string; email:string; district:string; state:string; category:string; lostMoney:string; bank:string; account:string; transactionId:string; transactionDate:string; amount:string; time:string; suspect:string; suspectBank:string; suspectAccount:string; suspectTransactionId:string; suspectDate:string; suspectAmount:string; platforms:string[]; otherPlatform:string; description:string }
const initial: FormData = { mobile:'',name:'',email:'',district:'',state:'',category:'',lostMoney:'',bank:'',account:'',transactionId:'',transactionDate:'',amount:'',time:'',suspect:'',suspectBank:'',suspectAccount:'',suspectTransactionId:'',suspectDate:'',suspectAmount:'',platforms:[],otherPlatform:'',description:'' }
type TrackingResult = { status?:string; alert_level?:string; actionable_intelligence?:string }

function Field({ label, required=true, error, children }: { label:string; required?:boolean; error?:string; children:React.ReactNode }) { return <label className="field"><span>{label}{required && <b> *</b>}</span>{children}{error && <small className="error">{error}</small>}</label> }
function Input(props: React.InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`control ${props.className || ''}`} /> }
function Select({ children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className="control">{children}</select> }
function Button({ children, secondary=false, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { secondary?:boolean }) { return <button {...props} className={`btn ${secondary ? 'btn-secondary' : ''} ${props.className || ''}`}>{children}</button> }

export default function Page() {
  const [step,setStep] = useState(1); const [data,setData] = useState<FormData>(initial); const [errors,setErrors] = useState<Record<string,string>>({}); const [otpSent,setOtpSent] = useState(false); const [otp,setOtp] = useState(['','','','','','']); const [seconds,setSeconds] = useState(45); const [ack,setAck] = useState(''); const [localSave,setLocalSave] = useState(false); const [declare,setDeclare] = useState(false); const [tracking,setTracking] = useState(false); const [trackValue,setTrackValue] = useState(''); const [trackingResult,setTrackingResult] = useState<TrackingResult|null>(null); const [trackingError,setTrackingError] = useState(''); const [trackingLoading,setTrackingLoading] = useState(false); const [mobileError,setMobileError] = useState('');
  useEffect(() => { if (otpSent && seconds > 0) { const t=setTimeout(()=>setSeconds(s=>s-1),1000); return ()=>clearTimeout(t) } }, [otpSent,seconds])
  const update=(key:keyof FormData,value:string|string[])=>setData(d=>({...d,[key]:value}))
  const validate=(target:number) => { const e:Record<string,string>={}; if(target===2){ if(!/^[A-Za-z ]{2,}$/.test(data.name))e.name='Enter your full name using letters and spaces only.'; if(!/^\S+@\S+\.\S+$/.test(data.email))e.email='Enter a valid email address.'; if(!data.district)e.district='City / District is required.'; if(!data.state)e.state='Select your state or union territory.' }
    if(target===3){ if(!data.category)e.category='Select a sub category.'; if(!data.lostMoney)e.lostMoney='Please select an option.'; if(data.lostMoney==='Yes'){if(!data.bank)e.bank='Select your bank.';if(!/^\d{9,18}$/.test(data.account))e.account='Enter 9–18 digits.';if(!/^[A-Za-z0-9]{6,24}$/.test(data.transactionId))e.transactionId='Enter 6–24 letters or numbers.';if(!data.transactionDate)e.transactionDate='Select the transaction date.';if(new Date(data.transactionDate)>new Date())e.transactionDate='Date cannot be in the future.';if(!(Number(data.amount)>0))e.amount='Enter an amount greater than ₹0.';if(!data.time)e.time='Select transaction time.'} if(!data.suspect)e.suspect='Please select an option.'; if(data.suspect==='Yes'){if(!data.suspectBank)e.suspectBank='Select suspect bank.';if(!data.suspectAccount)e.suspectAccount='Enter suspect account or UPI ID.'} if(!data.platforms.length)e.platforms='Select at least one platform.'; if(data.platforms.includes('Other')&&!data.otherPlatform)e.otherPlatform='Please specify the platform.';if(data.description.length<50)e.description='Description must be at least 50 characters.' }
    setErrors(e); return !Object.keys(e).length }
  const next=()=>{ if(step===1){if(!/^([6-9])\d{9}$/.test(data.mobile)){setMobileError('Enter a valid 10-digit mobile number starting with 6, 7, 8 or 9.');return} if(!otpSent){setOtpSent(true);setSeconds(45);return} if(otp.join('')!=='123456'){setMobileError('Incorrect OTP. Please try again.');return} setMobileError('');setStep(2)} else if(validate(step)){setStep(step+1)} }
  const submit=async()=>{ if(!declare){setErrors({declare:'Please accept the declaration to continue.'});return} const now=new Date();const number=`NCRP-${now.toISOString().slice(0,10).replaceAll('-','')}-${Math.floor(100000+Math.random()*900000)}`;setAck(number); const payload={acknowledgement_no:number,fraud_category:data.category,fraud_amount:Number(data.amount)||0,victim_name:data.name,victim_phone:`+91${data.mobile}`,victim_email:data.email,victim_bank:data.bank,victim_account_no:data.account,mule_bank_name:data.suspectBank,mule_account_no:data.suspectAccount,incident_timestamp:data.transactionDate?new Date(`${data.transactionDate}T${data.time||'12:00'}`).toISOString():now.toISOString(),state:data.state,district:data.district,incident_platforms:data.platforms,lost_money:data.lostMoney==='Yes',description:data.description,amount_lost:Number(data.amount)||0,suspect_transaction_id:data.suspectTransactionId,suspect_amount:Number(data.suspectAmount)||0,transaction_id:data.transactionId}; try {const res=await fetch('/api/complaints',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!res.ok)throw new Error('API');const result=await res.json();if(result.acknowledgement_no)setAck(result.acknowledgement_no);setLocalSave(false);setStep(5)}catch{setLocalSave(false);setErrors({submit:'Unable to save your complaint right now. Please try again.'})} }
  const trackComplaint=async()=>{ const value=trackValue.trim();if(!value)return;setTrackingLoading(true);setTrackingError('');setTrackingResult(null);try {const res=await fetch(`/api/complaints?id=${encodeURIComponent(value)}`);if(res.status===404){setTrackingError('Complaint not found. Please check your acknowledgement number.');return}if(!res.ok)throw new Error('API');const result=await res.json();setTrackingResult(result)}catch{setTrackingError('Unable to fetch complaint status. Please try again.')}finally{setTrackingLoading(false)} }
  const openTracking=()=>{setTracking(true);setTrackingError('');setTrackingResult(null)}
  const progress=step===5?100:Math.round((step/4)*100); const today=new Date().toISOString().slice(0,10); const trackingStatus=trackingResult?.status?.toUpperCase();
  return <div className="portal"><header><div className="header-inner"><div className="brand"><div className="chakra" aria-hidden="true">✺</div><div><strong>National Cybercrime<br/>Reporting Portal</strong><small>Ministry of Home Affairs | Government of India</small></div></div><div className="helpline"><span>Cyber Crime Helpline</span><a href="tel:1930"><Phone size={16}/>1930</a></div><Menu className="menu" /></div></header><div className="progress"><div style={{width:`${progress}%`}} /></div><main className="main"><div className="eyebrow"><ShieldCheck size={16}/> SECURE GOVERNMENT SERVICE <span><LockKeyhole size={14}/> Your information is protected</span></div>{step<5 && <div className="steps">{['Verify mobile','Your details','Complaint','Review'].map((s,i)=><div className={step===i+1?'active':step>i+1?'done':''} key={s}><i>{step>i+1?<Check size={14}/>:i+1}</i><span>{s}</span></div>)}</div>}
  {step===1 && <section className="card narrow"><div className="card-icon"><Phone/></div><h1>Verify Your Mobile Number</h1><p className="intro">We’ll send a one-time password to verify your mobile number before you file a complaint.</p><Field label="Mobile Number" error={mobileError}><div className="phone-input"><span>+91</span><Input autoFocus inputMode="numeric" maxLength={10} value={data.mobile} onChange={e=>{update('mobile',e.target.value.replace(/\D/g,''));setMobileError('')}} placeholder="Enter 10-digit mobile number" /></div></Field>{otpSent && <div className="otp-area"><label>Enter 6-digit OTP</label><div className="otp-row">{otp.map((v,i)=><Input key={i} value={v} maxLength={1} inputMode="numeric" aria-label={`OTP digit ${i+1}`} onChange={e=>{const copy=[...otp];copy[i]=e.target.value.replace(/\D/g,'');setOtp(copy);if(e.target.value&&i<5)(document.querySelectorAll('.otp-row input')[i+1] as HTMLInputElement)?.focus()}} />)}</div><p className="muted">{seconds>0?`Resend OTP in ${seconds}s`: <button className="link" onClick={()=>{setSeconds(45);setOtp([])}}>Resend OTP</button>}</p></div>}<Button onClick={next}>{otpSent?'Verify OTP':'Send OTP'} <ChevronRight size={18}/></Button><p className="demo">Demo mode: use OTP <b>123456</b></p><button className="link tracking-link" onClick={openTracking}>Track Existing Complaint</button></section>}
  {step===2 && <section className="card"><SectionTitle title="Complainant Information" subtitle="This information will be used to contact you regarding your complaint"/><div className="form-grid"><Field label="Full Name" error={errors.name}><Input value={data.name} onChange={e=>update('name',e.target.value)} placeholder="Enter your full name" /></Field><Field label="Mobile Number"><Input value={`+91 ${data.mobile}`} readOnly /></Field><Field label="Email ID" error={errors.email}><Input type="email" value={data.email} onChange={e=>update('email',e.target.value)} placeholder="name@example.com" /></Field><Field label="City / District" error={errors.district}><Input value={data.district} onChange={e=>update('district',e.target.value)} placeholder="Enter city or district" /></Field><Field label="State / Union Territory" error={errors.state}><Select value={data.state} onChange={e=>update('state',e.target.value)}><option value="">Select state / UT</option>{states.map(s=><option key={s}>{s}</option>)}</Select></Field></div><Nav back={()=>setStep(1)} next={next}/></section>}
  {step===3 && <section className="card"><SectionTitle title="Complaint Details" subtitle="Provide as much information as possible to help us investigate your complaint"/><h2>Crime Details</h2><div className="form-grid"><Field label="Sub Category" error={errors.category}><Select value={data.category} onChange={e=>update('category',e.target.value)}><option value="">Select crime category</option>{categories.map(c=><option key={c}>{c}</option>)}</Select></Field><RadioField label="Have you lost money?" value={data.lostMoney} error={errors.lostMoney} onChange={v=>update('lostMoney',v)}/></div>{data.lostMoney==='Yes'&&<><Divider title="Your Bank / Transaction Details"/><div className="form-grid"><Field label="Bank Name" error={errors.bank}><Select value={data.bank} onChange={e=>update('bank',e.target.value)}><option value="">Search or select bank</option>{banks.map(b=><option key={b}>{b}</option>)}</Select></Field><Field label="Account Number" error={errors.account}><Input inputMode="numeric" value={data.account} onChange={e=>update('account',e.target.value.replace(/\D/g,''))}/></Field><Field label="Transaction ID / UTR Number" error={errors.transactionId}><Input value={data.transactionId} onChange={e=>update('transactionId',e.target.value)}/></Field><Field label="Transaction Date" error={errors.transactionDate}><Input type="date" max={today} value={data.transactionDate} onChange={e=>update('transactionDate',e.target.value)}/></Field><Field label="Amount Lost (₹)" error={errors.amount}><Input type="number" min="1" value={data.amount} onChange={e=>update('amount',e.target.value)}/></Field><Field label="Approximate Time" error={errors.time}><Input type="time" value={data.time} onChange={e=>update('time',e.target.value)}/></Field></div></>}
  <Divider title="Suspect Details"/><RadioField label="Do you have suspect account details?" value={data.suspect} error={errors.suspect} onChange={v=>update('suspect',v)}/>{data.suspect==='Yes'&&<div className="form-grid suspect"><Field label="Suspect Bank Name" error={errors.suspectBank}><Select value={data.suspectBank} onChange={e=>update('suspectBank',e.target.value)}><option value="">Select bank</option>{banks.map(b=><option key={b}>{b}</option>)}</Select></Field><Field label="Suspect Account Number / UPI ID" error={errors.suspectAccount}><Input value={data.suspectAccount} onChange={e=>update('suspectAccount',e.target.value)}/></Field><Field label="Suspect Transaction ID"><Input value={data.suspectTransactionId} onChange={e=>update('suspectTransactionId',e.target.value)}/></Field><Field label="Suspect Transaction Date"><Input type="date" max={today} value={data.suspectDate} onChange={e=>update('suspectDate',e.target.value)}/></Field><Field label="Suspect Amount (₹)"><Input type="number" value={data.suspectAmount} onChange={e=>update('suspectAmount',e.target.value)}/></Field></div>}<Divider title="Incident Location"/><Field label="Where did the incident occur?" error={errors.platforms}><div className="checks">{platforms.map(p=><label className="check" key={p}><input type="checkbox" checked={data.platforms.includes(p)} onChange={e=>update('platforms',e.target.checked?[...data.platforms,p]:data.platforms.filter(x=>x!==p))}/><span>{p}</span></label>)}</div></Field>{data.platforms.includes('Other')&&<Field label="Other platform" error={errors.otherPlatform}><Input value={data.otherPlatform} onChange={e=>update('otherPlatform',e.target.value)}/></Field>}<Field label="Brief Description" error={errors.description}><textarea className="control textarea" maxLength={500} value={data.description} onChange={e=>update('description',e.target.value)} placeholder="Describe how the fraud occurred..."/><small className="counter">{data.description.length}/500</small></Field><Nav back={()=>setStep(2)} next={next}/></section>}
  {step===4 && <section className="card"><SectionTitle title="Review & Submit" subtitle="Please review your information carefully before submitting your complaint"/><div className="review-grid"><Review title="Complainant Information" items={[["Name",data.name],["Mobile",`+91 ${data.mobile}`],["Email",data.email],["Location",`${data.district}, ${data.state}`]]}/><Review title="Complaint Information" items={[["Category",data.category],["Lost money",data.lostMoney],["Bank",data.bank||'Not provided'],["Amount",data.amount?`₹${data.amount}`:'Not provided'],["Transaction ID",data.transactionId||'Not provided'],["Platforms",data.platforms.join(', ')]]}/></div><label className="declaration"><input type="checkbox" checked={declare} onChange={e=>setDeclare(e.target.checked)}/><span>I hereby declare that the information provided is true and correct to the best of my knowledge</span></label>{errors.declare&&<small className="error">{errors.declare}</small>}{errors.submit&&<small className="error">{errors.submit}</small>}<Nav back={()=>setStep(3)} next={submit} submit/></section>}
  {step===5 && <section className="card acknowledgement"><div className="success-icon"><Check/></div><h1>Complaint Registered Successfully</h1><p className="intro">Your complaint has been submitted to the National Cybercrime Reporting Portal.</p><div className="ack-number"><span>Acknowledgement Number</span><strong>{ack}</strong></div>{localSave&&<div className="save-notice">Your complaint has been saved locally. It will be synced when connectivity is restored.</div>}<div className="info-box"><b>What happens next?</b><p>You will receive updates on your registered email and mobile number. For urgent assistance call <strong>1930</strong>.</p></div><div className="summary-table"><div><span>Crime category</span><b>{data.category}</b></div><div><span>Amount reported</span><b>{data.amount?`₹${data.amount}`:'No monetary loss reported'}</b></div><div><span>Date filed</span><b>{new Date().toLocaleDateString('en-IN')}</b></div></div><div className="actions"><Button onClick={()=>window.print()}><Download size={17}/> Download Acknowledgement</Button><Button secondary onClick={openTracking}><FileText size={17}/> Track Your Complaint</Button></div></section>}</main><footer><div><b>National Cybercrime Reporting Portal</b><span>© 2026 Ministry of Home Affairs, Government of India</span></div><div><a>Disclaimer</a><a>Privacy Policy</a><a>Accessibility</a></div></footer>{tracking&&<div className="modal-backdrop" onClick={()=>setTracking(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setTracking(false)}><X/></button><h2>Track Your Complaint</h2><p>Enter your acknowledgement number to view the status of your complaint.</p><Input value={trackValue} onChange={e=>{setTrackValue(e.target.value);setTrackingError('');setTrackingResult(null)}} placeholder="NCRP-YYYYMMDD-XXXXXX"/><Button onClick={trackComplaint}>{trackingLoading?'Checking...':'Track Status'}</Button>{trackingError&&<p className="error tracking-message">{trackingError}</p>}{trackingResult&&<div className="tracking-result"><div className={`tracking-badge ${trackingStatus==='PROCESSED'?'processed':'investigation'}`}>{trackingStatus==='PROCESSED'?'Your complaint is being actively tracked':'Under Investigation'}</div><p><b>Status:</b> {trackingStatus==='PROCESSED'?'Processed':'Under Investigation'}</p>{trackingStatus==='PROCESSED'&&trackingResult.alert_level&&<p><b>Alert level:</b> {trackingResult.alert_level}</p>}{trackingResult.actionable_intelligence&&<p><b>Actionable intelligence:</b> {trackingResult.actionable_intelligence}</p>}</div>}</div></div>}</div>
}
function SectionTitle({title,subtitle}:{title:string;subtitle:string}){return <div className="section-title"><div><h1>{title}</h1><p>{subtitle}</p></div><span className="step-badge">Step</span></div>}
function Divider({title}:{title:string}){return <div className="divider"><span>{title}</span></div>}
function RadioField({label,value,error,onChange}:{label:string;value:string;error?:string;onChange:(v:string)=>void}){return <div className="radio-field"><span>{label} <b>*</b></span><div><label><input type="radio" checked={value==='Yes'} onChange={()=>onChange('Yes')}/> Yes</label><label><input type="radio" checked={value==='No'} onChange={()=>onChange('No')}/> No</label></div>{error&&<small className="error">{error}</small>}</div>}
function Nav({back,next,submit=false}:{back:()=>void;next:()=>void;submit?:boolean}){return <div className="nav"><Button secondary onClick={back}><ChevronLeft size={17}/> Back</Button><Button onClick={next}>{submit?'Submit Complaint':'Continue'} <ChevronRight size={17}/></Button></div>}
function Review({title,items}:{title:string;items:string[][]}){return <div className="review-box"><h2>{title}</h2>{items.map(([a,b])=><div key={a}><span>{a}</span><b>{b||'—'}</b></div>)}</div>}
